import type { ApiHandler } from "../_lib/http.js";
import { withMaintenanceGuard } from "../_lib/maintenance.js";
import { ok, err, getQueryParam, getClientIp, withEdgeCache } from "../_lib/http.js";
import { TtlCache, RateLimiter, fetchWithTimeout } from "../_lib/cache.js";

/**
 * Live situational layers, proxied server-side.
 *
 * On what's here and what isn't. The obvious wish-list for a layer like this
 * is earthquakes, wildfires, radar, air quality, traffic, flights and ships.
 * Only some of those have a genuinely free, keyless, public source:
 *
 *   included   USGS earthquakes      free, keyless, public GeoJSON feed
 *              RainViewer radar      free, keyless tile manifest
 *              Open-Meteo air quality free, keyless, and already this app's
 *                                    weather provider
 *
 *   excluded   NASA FIRMS wildfires  needs a (free) registered API key
 *              Live traffic          no free source exists at all
 *              Flights / ships       free tiers withdrawn or unusable
 *
 * The excluded ones are not stubbed, faked or shown as "coming soon"
 * toggles that do nothing - they're simply absent, and the panel says why.
 * A layer switch that produces no layer is worse than no switch.
 *
 * Everything is proxied rather than fetched from the browser because the
 * app's Content-Security-Policy only permits same-origin connections; that
 * also means one server-side cache serves every visitor instead of each
 * browser hitting these services independently.
 */

const USER_AGENT = "maNOWj-GeoIntel/2.0 (live layers; geospatial intelligence app)";

// Earthquake feeds are regenerated by USGS every minute or so, but nobody
// needs sub-5-minute freshness to see where today's quakes were, and this
// cache is what keeps a room full of demo viewers from becoming a hundred
// requests to a public service.
const quakeCache = new TtlCache<unknown>(5 * 60 * 1000);
// Radar frames advance roughly every ten minutes; 4 minutes keeps the newest
// frame current without re-fetching the manifest on every pan.
const radarCache = new TtlCache<unknown>(4 * 60 * 1000);
const airCache = new TtlCache<unknown>(15 * 60 * 1000);
const limiter = new RateLimiter(60_000, 40);

interface UsgsFeature {
  id: string;
  properties: { mag: number | null; place: string | null; time: number | null; url: string | null; title: string | null };
  geometry: { coordinates: [number, number, number] };
}

async function earthquakes(windowKey: string) {
  // USGS publishes one file per (magnitude, window) pair; only these two are
  // offered because a full "all earthquakes this month" feed is tens of
  // thousands of points and would make the map unreadable, not more useful.
  const feed = windowKey === "week" ? "2.5_week" : "all_day";
  const cached = quakeCache.get(feed);
  if (cached) return cached;

  const response = await fetchWithTimeout(
    `https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/${feed}.geojson`,
    { headers: { "User-Agent": USER_AGENT, Accept: "application/geo+json" } },
    9000
  );
  if (!response.ok) throw new Error(`USGS returned HTTP ${response.status}`);

  const data = (await response.json()) as { features?: UsgsFeature[] };
  const events = (data.features ?? [])
    .filter((f) => f.geometry?.coordinates && typeof f.properties?.mag === "number")
    .map((f) => ({
      id: f.id,
      magnitude: f.properties.mag as number,
      place: f.properties.place ?? f.properties.title ?? "Unknown location",
      time: f.properties.time,
      url: f.properties.url,
      lon: f.geometry.coordinates[0],
      lat: f.geometry.coordinates[1],
      depthKm: f.geometry.coordinates[2],
    }))
    .sort((a, b) => b.magnitude - a.magnitude);

  const payload = { events, source: "USGS Earthquake Hazards Program", fetchedAt: new Date().toISOString() };
  quakeCache.set(feed, payload);
  return payload;
}

async function radar() {
  const cached = radarCache.get("radar");
  if (cached) return cached;

  const response = await fetchWithTimeout("https://api.rainviewer.com/public/weather-maps.json", { headers: { "User-Agent": USER_AGENT } }, 8000);
  if (!response.ok) throw new Error(`RainViewer returned HTTP ${response.status}`);

  const data = (await response.json()) as { host?: string; radar?: { past?: Array<{ time: number; path: string }>; nowcast?: Array<{ time: number; path: string }> } };
  const frames = [...(data.radar?.past ?? []), ...(data.radar?.nowcast ?? [])];
  if (!data.host || frames.length === 0) throw new Error("RainViewer returned no radar frames");

  // Only the newest frame is used: an animated loop needs a frame scheduler,
  // preloading and a play/pause control, and a still radar image of the last
  // few minutes already answers "is it raining there".
  const latest = frames[frames.length - 1]!;
  const payload = {
    tileUrl: `${data.host}${latest.path}/256/{z}/{x}/{y}/2/1_1.png`,
    frameTime: latest.time,
    source: "RainViewer",
    fetchedAt: new Date().toISOString(),
  };
  radarCache.set("radar", payload);
  return payload;
}

interface AirQualityResponse {
  current?: { european_aqi?: number; us_aqi?: number; pm2_5?: number; pm10?: number; nitrogen_dioxide?: number; ozone?: number; time?: string };
}

async function airQuality(lat: number, lon: number) {
  const key = `${lat.toFixed(2)},${lon.toFixed(2)}`;
  const cached = airCache.get(key);
  if (cached) return cached;

  const url = new URL("https://air-quality-api.open-meteo.com/v1/air-quality");
  url.searchParams.set("latitude", String(lat));
  url.searchParams.set("longitude", String(lon));
  url.searchParams.set("current", "european_aqi,us_aqi,pm2_5,pm10,nitrogen_dioxide,ozone");

  const response = await fetchWithTimeout(url.toString(), { headers: { "User-Agent": USER_AGENT } }, 8000);
  if (!response.ok) throw new Error(`Open-Meteo air quality returned HTTP ${response.status}`);

  const data = (await response.json()) as AirQualityResponse;
  if (!data.current) throw new Error("Air quality provider returned no current reading");

  const payload = {
    europeanAqi: data.current.european_aqi ?? null,
    usAqi: data.current.us_aqi ?? null,
    pm25: data.current.pm2_5 ?? null,
    pm10: data.current.pm10 ?? null,
    no2: data.current.nitrogen_dioxide ?? null,
    ozone: data.current.ozone ?? null,
    observedAt: data.current.time ?? null,
    source: "Open-Meteo Air Quality (CAMS)",
    fetchedAt: new Date().toISOString(),
  };
  airCache.set(key, payload);
  return payload;
}

const handler: ApiHandler = async (req, res) => {
  const layer = getQueryParam(req, "layer");

  const rate = limiter.check(getClientIp(req));
  if (!rate.allowed) return err(res, 429, "Too many live-layer requests. Please slow down.", "RATE_LIMITED");

  try {
    if (layer === "earthquakes") {
      return ok(res, await earthquakes(getQueryParam(req, "window") ?? "day"));
    }

    if (layer === "radar") {
      return ok(res, await radar());
    }

    if (layer === "air-quality") {
      const lat = Number(getQueryParam(req, "lat"));
      const lon = Number(getQueryParam(req, "lon"));
      if (!Number.isFinite(lat) || !Number.isFinite(lon)) {
        return err(res, 400, "Air quality needs 'lat' and 'lon' query parameters.");
      }
      return ok(res, await airQuality(lat, lon));
    }

    return err(res, 400, "Unknown layer. Supported: earthquakes, radar, air-quality.", "UNKNOWN_LAYER");
  } catch (error) {
    console.error(`[api/live:${layer}]`, error);
    const reason = error instanceof Error ? error.message : "unknown reason";
    return err(res, 502, `This live layer is temporarily unavailable (${reason}).`, "PROVIDER_UNAVAILABLE");
  }
};

export default withMaintenanceGuard(withEdgeCache(240)(handler));
