/**
 * The cities that get their own page.
 *
 * The rule is "written properly", not a number — and it is worth stating that
 * precisely, because this file used to say "eight, not eighty" and that was
 * the wrong rule stated in the right spirit.
 *
 * What search engines have spent fifteen years learning to ignore is the
 * TEMPLATE: forty pages reading "X is a city in Y with a population of Z",
 * generated by a loop, each one a doorway to the same app. That is a real
 * hazard and nothing below is allowed to become it. But the defence against
 * it is that every entry here is researched and written for the one place it
 * describes, not that there are only a handful of them. Twelve written
 * properly beats eight written properly; eighty written by a loop beats
 * neither.
 *
 * So the bar for adding a city is: its coordinates, terrain and landmarks
 * were looked up in a source and checked, and the geography paragraph says
 * something true of that city and of nowhere else. A place that cannot clear
 * that bar — a town with no real geography to describe and almost nothing
 * mapped in it — would render as a page of "Not published", which is exactly
 * the thin page the hazard describes. It does not get an entry.
 *
 * WHAT IS IN THIS FILE, AND WHAT IS DELIBERATELY NOT.
 *
 * In: the things that do not change and that can be checked — the city's name,
 * the state it is in, its coordinates, the river or coast it sits on, a handful
 * of landmarks anyone can verify on the map itself.
 *
 * Not in: a single number. No population, no area, no density, no air quality,
 * no counts of hospitals or schools. Every figure on these pages is fetched
 * live from the same APIs the app uses, and arrives with its source and its
 * date attached. That is not caution for its own sake — a hardcoded population
 * is wrong the day it is written and gets more wrong every year, silently, in a
 * page that exists to look authoritative. This app's whole claim is that every
 * answer shows where it came from and when. A city page full of unsourced
 * numbers would be the one place that claim is false.
 *
 * The prose below is written per city rather than templated for the same
 * reason. "X is a city in Y with a population of Z" eight times is a doorway
 * page whatever the values are.
 */

export interface City {
  /** The URL segment: /maps/<slug>. */
  slug: string;
  name: string;
  state: string;
  lat: number;
  lon: number;
  /** How far in the map opens. Tighter for compact cores, wider for sprawl. */
  zoom: number;
  /** One sentence for the meta description and the page intro. */
  summary: string;
  /** Two or three sentences of real geography, specific to this place. */
  geography: string;
  /** Landmarks anyone can find on the map, so the page is checkable. */
  landmarks: string[];
  /**
   * Questions this app can genuinely answer here, phrased the way the parser
   * accepts. Listing a question the app cannot run would be the worst kind of
   * SEO page: one that ranks and then disappoints.
   */
  questions: string[];
}

export const CITIES: City[] = [
  {
    slug: "hyderabad",
    name: "Hyderabad",
    state: "Telangana",
    lat: 17.385,
    lon: 78.4867,
    zoom: 12,
    summary:
      "Hyderabad on an interactive map: ask what lies within any radius of a point on the Deccan plateau, from Charminar to HITEC City, with every figure showing its source.",
    geography:
      "Hyderabad sits on the Deccan plateau in Telangana, built along the Musi river and around a chain of artificial lakes, the largest of which is Hussain Sagar. The old city lies south of the river around Charminar; the newer technology districts run north-west through Madhapur and Gachibowli. Granite outcrops are visible across the whole urban area, which is why so much of the older architecture is built from it.",
    landmarks: ["Charminar", "Golconda Fort", "Hussain Sagar", "HITEC City", "Osmania University"],
    questions: [
      "hospitals within 5 km",
      "schools within 2 km",
      "what is within 800 m",
      "is this a good place for a restaurant",
    ],
  },
  {
    slug: "bengaluru",
    name: "Bengaluru",
    state: "Karnataka",
    lat: 12.9716,
    lon: 77.5946,
    zoom: 12,
    summary:
      "Bengaluru on an interactive map — a city built around rainwater tanks rather than a river. Ask what lies within any radius, with every figure showing where it came from.",
    geography:
      "Bengaluru sits high on the Deccan plateau, around 900 metres above sea level, which is why it stays cooler than most of southern India at the same latitude. It has no river running through it and grew instead around a network of tanks built to hold rainwater, many of which survive as lakes. The city spreads outward along the Outer Ring Road rather than from a single dense core.",
    landmarks: ["Lalbagh Botanical Garden", "Cubbon Park", "Vidhana Soudha", "Ulsoor Lake", "Electronic City"],
    questions: [
      "hospitals within 5 km",
      "cafes within 1 km",
      "what is within 800 m",
      "is this a good place for a restaurant",
    ],
  },
  {
    slug: "mumbai",
    name: "Mumbai",
    state: "Maharashtra",
    lat: 19.076,
    lon: 72.8777,
    zoom: 12,
    summary:
      "Mumbai on an interactive map: an island city that could only ever grow north. Ask what lies within any radius, with every figure showing its source and its date.",
    geography:
      "Mumbai occupies Salsette Island on India's west coast, which is the single fact that explains most of its geography: the city could only grow north, so it is long and narrow, and land is scarce in a way it is not anywhere else in the country. Sanjay Gandhi National Park sits inside the municipal boundary, which is unusual for a city this size. The western shoreline faces the Arabian Sea directly.",
    landmarks: ["Gateway of India", "Marine Drive", "Bandra-Worli Sea Link", "Sanjay Gandhi National Park", "Chhatrapati Shivaji Terminus"],
    questions: ["hospitals within 3 km", "schools within 1 km", "what is within 500 m", "banks within 1 km"],
  },
  {
    slug: "delhi",
    name: "Delhi",
    state: "Delhi",
    lat: 28.6139,
    lon: 77.209,
    zoom: 11,
    summary:
      "Delhi on an interactive map, from the Yamuna to the forested Ridge. Ask what lies within any radius of any point, with every figure showing its source and its date.",
    geography:
      "Delhi lies on the west bank of the Yamuna, on the flat Indo-Gangetic plain, interrupted by the Delhi Ridge — the northern tail of the Aravalli range, which runs through the city as a band of rocky, forested high ground. The National Capital Territory covers far more than the historic city, taking in New Delhi, the older walled city around Red Fort, and a wide belt of newer development.",
    landmarks: ["Red Fort", "India Gate", "Qutub Minar", "Connaught Place", "Lodhi Gardens"],
    questions: ["hospitals within 5 km", "schools within 2 km", "what is within 800 m", "pharmacies within 1 km"],
  },
  {
    slug: "chennai",
    name: "Chennai",
    state: "Tamil Nadu",
    lat: 13.0827,
    lon: 80.2707,
    zoom: 12,
    summary:
      "Chennai on an interactive map: the Coromandel coast, the Cooum and the Adyar. Ask what lies within any radius, with every figure showing the source it came from.",
    geography:
      "Chennai runs along the Coromandel Coast on the Bay of Bengal, on a flat coastal plain with almost no elevation change across the whole city. Two rivers cross it, the Cooum and the Adyar, joined by the Buckingham Canal running parallel to the shore. Marina Beach stretches for several kilometres along the eastern edge.",
    landmarks: ["Marina Beach", "Fort St George", "Kapaleeshwarar Temple", "Guindy National Park", "Adyar Estuary"],
    questions: ["hospitals within 5 km", "schools within 2 km", "what is within 800 m", "restaurants within 1 km"],
  },
  {
    slug: "pune",
    name: "Pune",
    state: "Maharashtra",
    lat: 18.5204,
    lon: 73.8567,
    zoom: 12,
    summary:
      "Pune on an interactive map, in the rain shadow of the Western Ghats. Ask what lies within any radius of any point, with every figure showing the source it came from.",
    geography:
      "Pune sits at the confluence of the Mula and Mutha rivers, on the leeward side of the Western Ghats about 560 metres above sea level. The Ghats to the west put it in a rain shadow, so it gets noticeably less monsoon rainfall than the coast sixty miles away. Hills sit inside the city itself, including Parvati and Vetal, which is why its road network bends around them rather than gridding.",
    landmarks: ["Shaniwar Wada", "Aga Khan Palace", "Parvati Hill", "Pashan Lake", "Hinjawadi"],
    questions: ["hospitals within 3 km", "schools within 2 km", "what is within 800 m", "cafes within 1 km"],
  },
  {
    slug: "kolkata",
    name: "Kolkata",
    state: "West Bengal",
    lat: 22.5726,
    lon: 88.3639,
    zoom: 12,
    summary:
      "Kolkata on an interactive map: the Hooghly, the Maidan and the East Kolkata Wetlands. Ask what lies within any radius, with every figure showing its source.",
    geography:
      "Kolkata stands on the east bank of the Hooghly, a distributary of the Ganges, roughly 60 kilometres inland from the Bay of Bengal. The land is almost entirely flat and only a few metres above sea level, part of the wider Ganges delta. East of the city lie the East Kolkata Wetlands, which treat much of its wastewater naturally and are a Ramsar site.",
    landmarks: ["Victoria Memorial", "Howrah Bridge", "Maidan", "Dakshineswar Kali Temple", "East Kolkata Wetlands"],
    questions: ["hospitals within 3 km", "schools within 2 km", "what is within 800 m", "banks within 1 km"],
  },
  {
    slug: "visakhapatnam",
    name: "Visakhapatnam",
    state: "Andhra Pradesh",
    lat: 17.6868,
    lon: 83.2185,
    zoom: 12,
    summary:
      "Visakhapatnam on an interactive map, where the Eastern Ghats run down to the Bay of Bengal. Ask what lies within any radius, with every figure showing its source.",
    geography:
      "Visakhapatnam sits between the Eastern Ghats and the Bay of Bengal, which gives it something almost no other large Indian city has: hills running right down to the shoreline. Its harbour is a natural one, sheltered by the Dolphin's Nose headland. The coastline here is steep enough that the beach road climbs and falls rather than running flat.",
    landmarks: ["Kailasagiri", "Dolphin's Nose", "RK Beach", "Simhachalam Temple", "Rushikonda Beach"],
    questions: ["hospitals within 3 km", "schools within 2 km", "what is within 800 m", "hotels within 2 km"],
  },
  {
    slug: "gurugram",
    name: "Gurugram",
    state: "Haryana",
    lat: 28.456,
    lon: 77.029,
    zoom: 12,
    summary:
      "Gurugram on an interactive map, where the Aravallis run out into the Delhi plain. Ask what lies within any radius, with every figure showing the source it came from.",
    geography:
      "Gurugram sits where the northern tail of the Aravalli range runs out into the Delhi plain, about 237 metres above sea level, drained by the seasonal Sahibi — a Yamuna tributary that rises in the Aravallis of Rajasthan. It went from a district town to a corporate centre in roughly three decades, which is why glass office blocks along the expressway stand directly against older village settlements instead of being separated from them by anything. Forested Aravalli remnants survive at Mangar Bani and Gwal Pahari, and Sultanpur National Park and the Basai wetland lie out to the west.",
    landmarks: ["Cyber City", "DLF CyberHub", "Sultanpur National Park", "Damdama Lake", "MG Road"],
    questions: ["hospitals within 3 km", "schools within 2 km", "what is within 800 m", "cafes within 1 km"],
  },
  {
    slug: "ahmedabad",
    name: "Ahmedabad",
    state: "Gujarat",
    lat: 23.03,
    lon: 72.58,
    zoom: 12,
    summary:
      "Ahmedabad on an interactive map, split east and west by the Sabarmati. Ask what lies within any radius of any point, with every figure showing its source.",
    geography:
      "Ahmedabad stands on the Sabarmati, which splits it cleanly in two: the walled old city and its dense pols on the east bank, the newer western districts across a line of bridges. The ground is flat, sandy and around 53 metres above sea level, broken only by the low Thaltej–Jodhpur rise. Two large lakes sit inside the built-up area — Kankaria, dug in 1451, and Vastrapur.",
    landmarks: ["Sabarmati Riverfront", "Kankaria Lake", "Sabarmati Ashram", "Vastrapur Lake", "Bhadra Fort"],
    questions: ["hospitals within 5 km", "schools within 2 km", "what is within 800 m", "parks within 2 km"],
  },
  {
    slug: "kochi",
    name: "Kochi",
    state: "Kerala",
    lat: 9.9312,
    lon: 76.2673,
    zoom: 12,
    summary:
      "Kochi on an interactive map: a mainland strip, a peninsula, and the islands between them. Ask what lies within any radius, with every figure showing its source.",
    geography:
      "Kochi is built across a lagoon rather than on one piece of ground: a mainland strip at Ernakulam, a peninsula at Fort Kochi, and a scatter of islands between them, tied together by bridges and ferries. Much of it lies at sea level, with roughly 48 kilometres of coastline on the Laccadive Sea. It sits on the windward side of the Western Ghats, which is why the monsoon reaches here early and hard.",
    landmarks: ["Fort Kochi", "Chinese fishing nets", "Mattancherry Palace", "Marine Drive", "Santa Cruz Basilica"],
    questions: ["hospitals within 3 km", "hotels within 2 km", "what is within 800 m", "restaurants within 1 km"],
  },
  {
    slug: "indore",
    name: "Indore",
    state: "Madhya Pradesh",
    lat: 22.7186,
    lon: 75.855,
    zoom: 12,
    summary:
      "Indore on an interactive map, on the Malwa plateau where the Kanh meets the Saraswati. Ask what lies within any radius, with every figure showing its source.",
    geography:
      "Indore sits on the Malwa plateau in western Madhya Pradesh, about 550 metres above sea level, where two small rivers meet — the Kanh and the Saraswati — which run through the older parts of the city rather than around them. The plateau is high enough to take the edge off the summer compared with the plains below it, and level enough that the city has spread outward in most directions with little to stop it.",
    landmarks: ["Rajwada Palace", "Lalbagh Palace", "Kanch Mandir", "Khajrana Ganesh Temple", "Manik Bagh"],
    questions: ["hospitals within 3 km", "schools within 2 km", "what is within 800 m", "shopping within 1 km"],
  },
];

export const CITY_BY_SLUG = new Map(CITIES.map((c) => [c.slug, c]));

/** Every path this set of pages owns, for App's known-path check and the sitemap. */
export const CITY_PATHS = CITIES.map((c) => `/maps/${c.slug}`);
